// `fleet profile [--cwd P]` — the per-project profile (design Move 5).
//
// A compact, durable note about a project the Captain loads on RE-ENTRY (instead
// of re-deriving everything): the stack, how much has been delegated here, the
// recent objectives, and the verify pass/fail record. Deterministic — built from
// the outcome log + the currency table, no inference.
import { writeFileSync, mkdirSync, existsSync, readFileSync } from "node:fs";
import { join, basename } from "node:path";
import { CLAUDE_DOCS_DIR, versionsMdPath } from "../project-memory.js";
import { readOutcomes } from "../outcomes.js";

export function profile(opts: { cwd?: string } = {}): string {
  const cwd = opts.cwd ?? process.cwd();

  // Outcomes for work done in this project (cwd match, incl. worktrees under it).
  const mine = readOutcomes().filter((o) => o.cwd && (o.cwd === cwd || o.cwd.startsWith(cwd + "/")));
  const spawns = mine.filter((o) => o.event === "spawn");
  const verifies = mine.filter((o) => o.event === "verify");
  const passes = verifies.filter((v) => v.verdict === "pass").length;
  const fails = verifies.filter((v) => v.verdict === "fail").length;
  const recent = spawns.slice(-6).reverse().map((s) => `- ${(s.objective || "(no objective)").slice(0, 110)}`);

  // Stack line from the currency table, if one exists. Parse ONLY the packages
  // table (everything before the "## Current LLM model IDs" heading).
  let stack = "_(run `fleet currency` to populate)_";
  const vpath = versionsMdPath(cwd);
  if (existsSync(vpath)) {
    try {
      const pkgSection = readFileSync(vpath, "utf8").split(/^##\s+Current LLM model IDs/m)[0]!;
      const rows = pkgSection
        .split("\n")
        .filter((l) => l.startsWith("| ") && !l.includes("package | pinned") && !/^\|\s*-+/.test(l));
      const pkgs = rows.map((r) => r.split("|")[1]?.trim()).filter(Boolean).slice(0, 12);
      if (pkgs.length) stack = pkgs.join(", ");
    } catch {
      // leave default
    }
  }

  const body = [
    `# Project profile — ${basename(cwd)}`,
    ``,
    `_Auto-generated by \`fleet profile\` from the delegation-outcome log. Load this on re-entry._`,
    ``,
    `- path: \`${cwd}\``,
    `- delegations here: ${spawns.length}`,
    `- verify record: ${passes} pass / ${fails} fail`,
    ``,
    `## Stack`,
    stack,
    ``,
    `## Recent objectives`,
    recent.length ? recent.join("\n") : "_(none logged yet)_",
    ``,
  ].join("\n");

  const dir = join(cwd, CLAUDE_DOCS_DIR);
  mkdirSync(dir, { recursive: true });
  const path = join(dir, "profile.md");
  writeFileSync(path, body);
  return path;
}
